### ISSUE TITLE
Some odd Unicode text show up as squares out of the box unless ttf-ancient-fonts package is installed

### ISSUE THREAD

**Issue by sprite-1** [elementary/seeds#8] opened 2019-12-21 19:45 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
On fresh install, elementary OS would show some stylized Unicode text as squares unless you install `ttf-ancient-fonts` package from `apt`.

### To Reproduce
1. Fresh install of elementary OS (Juno or Hera)
2. Try to view this text -> 𝗟𝗼𝘂𝗻𝗴𝗲
3. It appears as a bunch of boxes

### Expected behavior

It should read out as "Lounge" in a bold text

## Platform Information
 - OS: elementary OS
 - OS Version: Juno or Hera

**Comment by jepotter1-archive** [comment] 2021-04-05 19:57
I'm on Odin and I can't reproduce this issue. Can you reproduce on Odin?

**Comment by hanaral** [comment] 2021-04-06 12:59
I'm afraid he isn't using elementary right now, but I can't reproduce it either. It might be OK to close this issue

**Comment by danirabbit** [comment] 2021-04-06 15:33
Gonna close since noto should be fulfilling this purpose these days

**Closed as completed by danirabbit** 2021-04-06 15:33 UTC
